wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
dataset:
  desc: null
  value: plank2
optimizer:
  desc: null
  value: adamW
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697090928.98064
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.17
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
